### ISSUE TITLE
Add an option to disable geolocation

### ISSUE THREAD

**Issue by tremby** [bence-toth/react-hook-geolocation#51]
Best practice is to only try to geolocate the user on the user's request, or at least when it's clear to the user why the browser is asking for their location.

React doesn't let us conditionally use hooks, short of conditionally rendering the component itself which uses the hook. If I make a conditionally-rendered nested component and use the hook from there, I'd need to pass the location data up the tree back to the parent component, which is not the React way.

I'd like to see an `enable` (default true) or `disable` (default false) option, so I can still use the hook but not have it actually do anything until I flip that option in response to the user saying "geolocate me".

**Comment by bence-toth** [comment]
Hi @tremby, thanks for this, it makes perfect sense to me.

Would you mind opening a PR which adds this option?

**Comment by bence-toth** [comment]
Thank you @tremby 🙌
