### ISSUE TITLE
How to convert speed to Km/h

### ISSUE THREAD

**Issue by nosed07** [bence-toth/react-hook-geolocation#55]
Hi all!

I am not sure what type of value is the speed. how could I convert it to km/h?

Thanks & I hope you guys can give me a heads up.

**Comment by bence-toth** [comment]
Hi @nosed07, thank you for reaching out. [According to MDN](https://developer.mozilla.org/en-US/docs/Web/API/GeolocationCoordinates/speed) it's meters/second.

**Comment by nosed07** [comment]
Thank you for your promp answer! You are right, I do not know how I passed it. :D
