### ISSUE TITLE
Is geolocation.heading the bearing?

### ISSUE THREAD

**Issue by nosed07** [bence-toth/react-hook-geolocation#56]
Hi again, thanks a lot for your help in advance.

Just wondering if the bearing (direction in wich the movil is moving) is represented by the geolocation.heading.
I am not sure how to understand this data value.

Thank you

**Comment by bence-toth** [comment]
Hi @nosed07 👋 

[According to MDN](https://developer.mozilla.org/en-US/docs/Web/API/GeolocationCoordinates/heading):

> The `heading` is a double representing the direction in which the device is traveling. This value, specified in degrees, indicates how far off from heading due north the device is. 0 degrees represents true north, and the direction is determined clockwise (which means that east is 90 degrees and west is 270 degrees). If `GeolocationCoordinates.speed` is `0`, heading is `NaN`. If the device is not able to provide heading information, this value is `null`.

I hope this helps.
