### ISSUE TITLE
Setting to control GPS recursivity

### ISSUE THREAD

**Issue by nosed07** [bence-toth/react-hook-geolocation#57]
Hi there again 👯 

I am using the hook and is updating data every two seconds or so.
Just wondering if there is a setting to control this behavoir and set this time to ms if possible?

Thanks!

**Comment by bence-toth** [comment]
According to MDN the Geolocation API doesn't provide a way to control the update frequency. I would imagine that it depends both on the browser and the device.

If you want less frequent updates, I guess you could combine the hook with some logic that debounces the value.

**Comment by nosed07** [comment]
Thanks a lot for your answer, you are always very helpful!
